# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate the R² value
#' @name calculate_r2
#' @param y_true The vector of true values.
#' @param y_pred The vector of predicted values.
#' @return Returns the R² value, which represents the goodness of fit of the model.
#' @export
calculate_r2 <- function(y_true, y_pred) {
    .Call(`_SA24204182_calculate_r2`, y_true, y_pred)
}

#' @title Calculate the Mean Squared Error (MSE)
#' @name calculate_mse
#' @param y_true The vector of true values.
#' @param y_pred The vector of predicted values.
#' @return Returns the Mean Squared Error (MSE).
#' @export
calculate_mse <- function(y_true, y_pred) {
    .Call(`_SA24204182_calculate_mse`, y_true, y_pred)
}

#' @title Gradient Descent with L2 Regularization for Optimizing Linear Regression Parameters
#' @name gradient_descent_with_regularization
#' @param X Input data matrix, where each row represents a sample and each column represents a feature.
#' @param y The vector of the target variable.
#' @param learning_rate The learning rate that controls the step size of each update.
#' @param iterations The number of iterations for gradient descent.
#' @param lambda The penalty coefficient for L2 regularization, used to prevent overfitting.
#' @return Returns the optimized regression coefficients (theta).
#' @export
gradient_descent_with_regularization <- function(X, y, learning_rate, iterations, lambda) {
    .Call(`_SA24204182_gradient_descent_with_regularization`, X, y, learning_rate, iterations, lambda)
}

